# Generated by Django 4.1.7 on 2023-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("temp", models.CharField(max_length=255)),
                ("humudity", models.CharField(max_length=255)),
                ("desiredTemp", models.CharField(max_length=255)),
                ("home_name", models.CharField(max_length=255)),
                ("door_status", models.BooleanField()),
                ("fan_status", models.BooleanField()),
                ("light_status", models.BooleanField()),
            ],
        ),
    ]
