# Generated by Django 4.1.7 on 2023-04-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTable",
            fields=[
                (
                    "user_id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("card_number", models.CharField(max_length=255)),
                ("active_status", models.BooleanField()),
                ("home_name", models.CharField(max_length=255)),
                ("approve_status", models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name="hometable",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="smarthome.usertable"
            ),
        ),
    ]
