# Generated by Django 4.1.7 on 2023-04-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarthome", "0003_homeinfotable_userinfotable_delete_hometable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homeName", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="homeinfotable",
            name="home_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarthome.homename",
            ),
        ),
        migrations.AlterField(
            model_name="userinfotable",
            name="home_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="smarthome.homename",
            ),
        ),
    ]
